export const SUPABASE_URL = 'http://jetson-local.hamr.top:8000';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzY1NzI4MDAwLCJleHAiOjE5MjM0OTQ0MDB9.TvUdo_Zg_svi6SwUiwJtqKatjkbqEw_pCZznEkHDRh4';
